### PR TITLE
Fix #694 - create user with correct username.

### LINKED ISSUE #694: When user mapping is not done on username field, initial user creation uses an invalid username.
When saml config is set up to map something like Moodle ID Number with an external value and also set to create new users, 

this line:
https://github.com/catalyst/moodle-auth_saml2/blob/MOODLE_39_STABLE/classes/auth.php#L664

Will create a new user account, but will populate the username field with the external "idnumber" value.

Then immediately after - it will replace the username with the correct value here:
https://github.com/catalyst/moodle-auth_saml2/blob/MOODLE_39_STABLE/classes/auth.php#L724

This can cause some weird edge case issues where an account already exists with the external idnumber stored as a username in  moodle (so the user creation causes a db  failure on the username index)

This is dodgy anyway - it should create the new user record and use the correct external username rather than creating a user record with an incorrect username.

### PR DESCRIPTION
**Pull request by danmarsden**
untested patch to create username with correct username when username is not the uid.

### CODE REVIEW

File: classes/auth.php [hunk 1]
```diff
@@ -962,6 +968,21 @@ public function get_email_from_attributes(array $attributes) {
...
     }
 
+    /**
+     * Get lowercase username from attributes, force as lowercase because Moodle requires it.
+     *
+     * @param array $attributes A list of attributes.
+     *
+     * @return bool
+     */
+    private function get_username_from_attributes(array $attributes) {
```
Comment (Peterburnett) [inline classes/auth.php:978]: Probably worth adding the return type hint

File: classes/auth.php [hunk 2]
```diff
@@ -962,6 +968,21 @@ public function get_email_from_attributes(array $attributes) {
...
+        if (!empty($this->config->field_map_username) && !empty($attributes[$this->config->field_map_username])) {
+            return strtolower($attributes[$this->config->field_map_username][0]);
```
Comment (Peterburnett) [inline classes/auth.php:980]: Could this ever be a string not an array in the SAML response?

Comment (danmarsden) [reply classes/auth.php:980]: good thought - I traced through the code to see where it would usually set the username value in the update_user call and found:
https://github.com/catalyst/moodle-auth_saml2/blob/MOODLE_39_STABLE/classes/auth.php#L924

Which shows it's always treated as an array in the existing code, so we can leave this for now and come back to it later if needed.

File: classes/auth.php (hunk 1 above)
Comment (danmarsden) [reply classes/auth.php:978]: hmm - return type is actually mixed string|bool - so I'll update the phpdoc, but there isn't a php 7 compat way of adding in the return type mixed on the function is there?

Comment (Peterburnett) [reply classes/auth.php:978]: No dont think there is :(

**Review by Peterburnett — APPROVED** [review]
